### ISSUE TITLE
HoverMany and Hover don't actually hover

### ISSUE THREAD

**Issue by Munksgaard** [terezka/line-charts#59]
[Ellie link](https://ellie-app.com/3X5v6D8PV8Sa1)

I've tried to port [the first example from the old version](https://terezka.github.io/line-charts/) to 0.19, but the `hoverMany` function seems to work differently from what it did back then. I would expect `hoverMany` to create a little box next to the cursor or the actual point in question, but instead it seems like a box is added at the bottom of the chart. The same happens if I try to use `hover`

Am I missing something?

**Comment by yuzisee** [comment]
Apparently a typo (created during migration to 0.19?) introduced on Oct 27, 2018

https://github.com/terezka/line-charts/commit/a92d43dedb623823fe09d8cdfe26ce016b30d867#r31813341

**Comment by Munksgaard** [comment]
Certainly looks like it.

**Comment by jartsap** [comment]
Hi, is there any hope that this would be fixed in near future?

**Comment by LiberalArtist** [comment]
I believe this is fixed by #58, which was merged recently, but there isn't a new version on https://package.elm-lang.org yet.

**Comment by QuinnFreedman** [comment]
I can confirm that I am still getting this error in `2.0.0` (the current version on [package.elm-lang.org](https://package.elm-lang.org/packages/terezka/line-charts/2.0.0/)) and it's causing me a lot of trouble. 

Is there any chance of getting a new package version with this fix?

**Comment by LiberalArtist** [comment]
I've vendored this package in as a Git submodule to get the fix from #58, and I can report that it's working great for us.
